language: python
python:
    - "2.7"
    - "3.6"
install:
    - python setup.py install
script:
    - python setup.py test
    - python -c 'from zenoss_client import ZenossClient; ZenossClient(host="", user="", passwd="", verify=False)'
